CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Type" character varying(50) NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Ranks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "RequiredEmbers" integer NOT NULL,
    "SvgIcon" text NOT NULL,
    CONSTRAINT "PK_Ranks" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Username" character varying(50) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Role" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "FullName" character varying(100) NOT NULL,
    "Bio" character varying(500) NOT NULL,
    "AvatarUrl" character varying(255) NOT NULL,
    "CoverUrl" character varying(255) NOT NULL,
    "SelectedBorderUrl" character varying(255) NOT NULL,
    "SelectedBannerUrl" character varying(255) NOT NULL,
    "ResetToken" character varying(6),
    "ResetTokenExpiry" timestamp with time zone,
    "TotalEmbers" integer NOT NULL,
    "RankId" integer,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Ranks_RankId" FOREIGN KEY ("RankId") REFERENCES "Ranks" ("Id")
);

CREATE TABLE "EmberTransactions" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ActionType" character varying(50) NOT NULL,
    "TargetId" uuid NOT NULL,
    "Points" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EmberTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmberTransactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Projects" (
    "Id" uuid NOT NULL,
    "Title" character varying(255) NOT NULL,
    "Description" text NOT NULL,
    "SourceCodeUrl" text NOT NULL,
    "ThumbnailUrl" text NOT NULL,
    "DownloadCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Projects_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserFollows" (
    "FollowersId" uuid NOT NULL,
    "FollowingId" uuid NOT NULL,
    CONSTRAINT "PK_UserFollows" PRIMARY KEY ("FollowersId", "FollowingId"),
    CONSTRAINT "FK_UserFollows_Users_FollowersId" FOREIGN KEY ("FollowersId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserFollows_Users_FollowingId" FOREIGN KEY ("FollowingId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CategoryProject" (
    "CategoriesId" integer NOT NULL,
    "ProjectsId" uuid NOT NULL,
    CONSTRAINT "PK_CategoryProject" PRIMARY KEY ("CategoriesId", "ProjectsId"),
    CONSTRAINT "FK_CategoryProject_Categories_CategoriesId" FOREIGN KEY ("CategoriesId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CategoryProject_Projects_ProjectsId" FOREIGN KEY ("ProjectsId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Comments" (
    "Id" uuid NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Comments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Ratings" (
    "Id" uuid NOT NULL,
    "StarValue" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    CONSTRAINT "PK_Ratings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Ratings_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Ratings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (1, 'C# / .NET', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (2, 'PHP', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (3, 'Java', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (4, 'JavaScript / React', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (5, 'Python', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (6, 'C / C++', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (7, 'Go', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (8, 'Ruby', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (9, 'Swift', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (10, 'Kotlin', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (11, 'Rust', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (12, 'TypeScript', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (13, 'SQL', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (14, 'Dart / Flutter', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (15, 'Ngôn ngữ Khác', 'NgonNgu');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (16, 'Nhập môn lập trình', 'MonHoc');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (17, 'Kỹ thuật lập trình', 'MonHoc');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (18, 'Lập trình hướng đối tượng (OOP)', 'MonHoc');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (19, 'Cấu trúc dữ liệu và giải thuật', 'MonHoc');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (20, 'Cơ sở dữ liệu', 'MonHoc');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (21, 'Phân tích thiết kế hệ thống', 'MonHoc');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (22, 'Phát triển ứng dụng Web', 'MonHoc');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (23, 'Phát triển ứng dụng Di động', 'MonHoc');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (24, 'Trí tuệ nhân tạo / Học máy', 'MonHoc');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (25, 'Đồ án / Khóa luận tốt nghiệp', 'MonHoc');
INSERT INTO "Categories" ("Id", "Name", "Type")
VALUES (26, 'Môn học Khác', 'MonHoc');

INSERT INTO "Ranks" ("Id", "Name", "RequiredEmbers", "SvgIcon")
VALUES (1, 'Kẻ Lưu Đày', 0, 'rank1');
INSERT INTO "Ranks" ("Id", "Name", "RequiredEmbers", "SvgIcon")
VALUES (2, 'Kẻ Nhóm Lửa', 50, 'rank2');
INSERT INTO "Ranks" ("Id", "Name", "RequiredEmbers", "SvgIcon")
VALUES (3, 'Kỵ Sĩ Thuật Toán', 120, 'rank3');
INSERT INTO "Ranks" ("Id", "Name", "RequiredEmbers", "SvgIcon")
VALUES (4, 'Ma Tôn Dữ Liệu', 250, 'rank4');
INSERT INTO "Ranks" ("Id", "Name", "RequiredEmbers", "SvgIcon")
VALUES (5, 'Lãnh Chúa Tro Tàn', 500, 'rank5');

INSERT INTO "Users" ("Id", "AvatarUrl", "Bio", "CoverUrl", "CreatedAt", "Email", "FullName", "PasswordHash", "RankId", "ResetToken", "ResetTokenExpiry", "Role", "SelectedBannerUrl", "SelectedBorderUrl", "TotalEmbers", "Username")
VALUES ('11111111-1111-1111-1111-111111111111', 'https://placehold.co/400x400/0a0a0c/d4af37?text=LordAdmin', 'Người duy trì trật tự của BonfireCode.', '', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'admin@bonfirecode.com', 'Tòa Án Tối Cao', '$2a$11$T2bGDzWt7VtIJerTTo2gIuoXReuPtF51Mu9bovy4aAk50bLaI0jxG', 5, NULL, NULL, 'Admin', '', '', 9999, 'LordAdmin');

CREATE INDEX "IX_CategoryProject_ProjectsId" ON "CategoryProject" ("ProjectsId");

CREATE INDEX "IX_Comments_ProjectId" ON "Comments" ("ProjectId");

CREATE INDEX "IX_Comments_UserId" ON "Comments" ("UserId");

CREATE INDEX "IX_EmberTransactions_UserId" ON "EmberTransactions" ("UserId");

CREATE INDEX "IX_Projects_UserId" ON "Projects" ("UserId");

CREATE INDEX "IX_Ratings_ProjectId" ON "Ratings" ("ProjectId");

CREATE INDEX "IX_Ratings_UserId" ON "Ratings" ("UserId");

CREATE INDEX "IX_UserFollows_FollowingId" ON "UserFollows" ("FollowingId");

CREATE INDEX "IX_Users_RankId" ON "Users" ("RankId");

SELECT setval(
    pg_get_serial_sequence('"Categories"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Categories") + 1,
        nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Ranks"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Ranks") + 1,
        nextval(pg_get_serial_sequence('"Ranks"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260719113955_InitialCreatePostgres', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE TABLE "Notifications" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "ActionUrl" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260724114229_AddNotifications', '8.0.8');

COMMIT;

