// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeShareAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260716070408_AddDownloadCount")]
    partial class AddDownloadCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CategoryProject", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectsId")
                        .HasColumnType("char(36)");

                    b.HasKey("CategoriesId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("CategoryProject");
                });

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C# / .NET",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PHP",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Java",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 4,
                            Name = "JavaScript / React",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Python",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 6,
                            Name = "C / C++",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Go",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ruby",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Swift",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kotlin",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Rust",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 12,
                            Name = "TypeScript",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 13,
                            Name = "SQL",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dart / Flutter",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ngôn ngữ Khác",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Nhập môn lập trình",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Kỹ thuật lập trình",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Lập trình hướng đối tượng (OOP)",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Cấu trúc dữ liệu và giải thuật",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Cơ sở dữ liệu",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Phân tích thiết kế hệ thống",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Phát triển ứng dụng Web",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Phát triển ứng dụng Di động",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Trí tuệ nhân tạo / Học máy",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Đồ án / Khóa luận tốt nghiệp",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Môn học Khác",
                            Type = "MonHoc"
                        });
                });

            modelBuilder.Entity("Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceCodeUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("StarValue")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CategoryProject", b =>
                {
                    b.HasOne("Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Comment", b =>
                {
                    b.HasOne("Entities.Project", "Project")
                        .WithMany("Comments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Project", b =>
                {
                    b.HasOne("Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Rating", b =>
                {
                    b.HasOne("Entities.Project", "Project")
                        .WithMany("Ratings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Project", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Projects");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
