// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeShareAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryProject", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectsId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("CategoryProject");
                });

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C# / .NET",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PHP",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Java",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 4,
                            Name = "JavaScript / React",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Python",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 6,
                            Name = "C / C++",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Go",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ruby",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Swift",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kotlin",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Rust",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 12,
                            Name = "TypeScript",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 13,
                            Name = "SQL",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dart / Flutter",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ngôn ngữ Khác",
                            Type = "NgonNgu"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Nhập môn lập trình",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Kỹ thuật lập trình",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Lập trình hướng đối tượng (OOP)",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Cấu trúc dữ liệu và giải thuật",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Cơ sở dữ liệu",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Phân tích thiết kế hệ thống",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Phát triển ứng dụng Web",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Phát triển ứng dụng Di động",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Trí tuệ nhân tạo / Học máy",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Đồ án / Khóa luận tốt nghiệp",
                            Type = "MonHoc"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Môn học Khác",
                            Type = "MonHoc"
                        });
                });

            modelBuilder.Entity("Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Entities.EmberTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmberTransactions");
                });

            modelBuilder.Entity("Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceCodeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Entities.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RequiredEmbers")
                        .HasColumnType("integer");

                    b.Property<string>("SvgIcon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kẻ Lưu Đày",
                            RequiredEmbers = 0,
                            SvgIcon = "rank1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kẻ Nhóm Lửa",
                            RequiredEmbers = 50,
                            SvgIcon = "rank2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kỵ Sĩ Thuật Toán",
                            RequiredEmbers = 120,
                            SvgIcon = "rank3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ma Tôn Dữ Liệu",
                            RequiredEmbers = 250,
                            SvgIcon = "rank4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lãnh Chúa Tro Tàn",
                            RequiredEmbers = 500,
                            SvgIcon = "rank5"
                        });
                });

            modelBuilder.Entity("Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("StarValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RankId")
                        .HasColumnType("integer");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SelectedBannerUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SelectedBorderUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TotalEmbers")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AvatarUrl = "https://placehold.co/400x400/0a0a0c/d4af37?text=LordAdmin",
                            Bio = "Người duy trì trật tự của BonfireCode.",
                            CoverUrl = "",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bonfirecode.com",
                            FullName = "Tòa Án Tối Cao",
                            PasswordHash = "$2a$11$T2bGDzWt7VtIJerTTo2gIuoXReuPtF51Mu9bovy4aAk50bLaI0jxG",
                            RankId = 5,
                            Role = "Admin",
                            SelectedBannerUrl = "",
                            SelectedBorderUrl = "",
                            TotalEmbers = 9999,
                            Username = "LordAdmin"
                        });
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<Guid>("FollowersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uuid");

                    b.HasKey("FollowersId", "FollowingId");

                    b.HasIndex("FollowingId");

                    b.ToTable("UserFollows", (string)null);
                });

            modelBuilder.Entity("CategoryProject", b =>
                {
                    b.HasOne("Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Comment", b =>
                {
                    b.HasOne("Entities.Project", "Project")
                        .WithMany("Comments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.EmberTransaction", b =>
                {
                    b.HasOne("Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Project", b =>
                {
                    b.HasOne("Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Rating", b =>
                {
                    b.HasOne("Entities.Project", "Project")
                        .WithMany("Ratings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.HasOne("Entities.Rank", "Rank")
                        .WithMany("Users")
                        .HasForeignKey("RankId");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("Entities.User", null)
                        .WithMany()
                        .HasForeignKey("FollowersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.User", null)
                        .WithMany()
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Project", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Entities.Rank", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Projects");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
